### ISSUE TITLE
Peer-Peer-Code-Review

### ISSUE THREAD

**Issue by 29td** [peterdtitan/to-do-list#8]
### Good job so far in implementing you project correctly.
_Projects functionality is great ✔️ 
Great styling ✔️ _

### Suggestions:
_I suggest that you make your list editable eg correcting the spelling or grammar.
Add the live link to your README file  and app screenshot (optional).
However the is nothing else to add.
Happy coding!_

**Comment by torobucci** [comment]
Hi @peterdtitan  👋

Great job on performing tests on your To-Do list app using jest.👍

# Highlights

- Great use of `describe()` method
- Good mocking of the HTML ✔

# Suggestions
I would make suggestions to make your project much better

- It would be better to add a live demo link to your project in order for viewers to clearly see your project
